version: "3.8"
services:
  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  fastapi:
    restart: always
    build:
      context: .
      dockerfile: BackendFastAPI/Dockerfile
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017
    ports:
      - "8080:8080"
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080"]

volumes:
  mongo_data:
